# 기본 빌드 설정
[build]
  command = "npm install recharts axios react-chartjs-2 chart.js prop-types --legacy-peer-deps && npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

# SPA 라우팅 처리
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200