/**
 * 부하 최적화 액션 타입
 */

// 부하 데이터 조회
export const FETCH_LOAD_DATA_REQUEST = 'FETCH_LOAD_DATA_REQUEST';
export const FETCH_LOAD_DATA_SUCCESS = 'FETCH_LOAD_DATA_SUCCESS';
export const FETCH_LOAD_DATA_FAILURE = 'FETCH_LOAD_DATA_FAILURE';

// 리소스별 부하 분석
export const FETCH_RESOURCE_LOAD_REQUEST = 'FETCH_RESOURCE_LOAD_REQUEST';
export const FETCH_RESOURCE_LOAD_SUCCESS = 'FETCH_RESOURCE_LOAD_SUCCESS';
export const FETCH_RESOURCE_LOAD_FAILURE = 'FETCH_RESOURCE_LOAD_FAILURE';

// 부하 최적화 추천 사항
export const FETCH_OPTIMIZATION_RECOMMENDATIONS_REQUEST = 'FETCH_OPTIMIZATION_RECOMMENDATIONS_REQUEST';
export const FETCH_OPTIMIZATION_RECOMMENDATIONS_SUCCESS = 'FETCH_OPTIMIZATION_RECOMMENDATIONS_SUCCESS';
export const FETCH_OPTIMIZATION_RECOMMENDATIONS_FAILURE = 'FETCH_OPTIMIZATION_RECOMMENDATIONS_FAILURE';

// 작업 자동 재분배
export const AUTO_DISTRIBUTE_TASKS_REQUEST = 'AUTO_DISTRIBUTE_TASKS_REQUEST';
export const AUTO_DISTRIBUTE_TASKS_SUCCESS = 'AUTO_DISTRIBUTE_TASKS_SUCCESS';
export const AUTO_DISTRIBUTE_TASKS_FAILURE = 'AUTO_DISTRIBUTE_TASKS_FAILURE';

// 부하 최적화 적용
export const APPLY_LOAD_OPTIMIZATION_REQUEST = 'APPLY_LOAD_OPTIMIZATION_REQUEST';
export const APPLY_LOAD_OPTIMIZATION_SUCCESS = 'APPLY_LOAD_OPTIMIZATION_SUCCESS';
export const APPLY_LOAD_OPTIMIZATION_FAILURE = 'APPLY_LOAD_OPTIMIZATION_FAILURE';

// 부하 예측 분석
export const PREDICT_FUTURE_LOAD_REQUEST = 'PREDICT_FUTURE_LOAD_REQUEST';
export const PREDICT_FUTURE_LOAD_SUCCESS = 'PREDICT_FUTURE_LOAD_SUCCESS';
export const PREDICT_FUTURE_LOAD_FAILURE = 'PREDICT_FUTURE_LOAD_FAILURE';

// 부하 최적화 UI 상태 관리
export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const SET_SELECTED_TEAM = 'SET_SELECTED_TEAM';
export const SET_SELECTED_RESOURCES = 'SET_SELECTED_RESOURCES';
export const SET_LOAD_THRESHOLD = 'SET_LOAD_THRESHOLD';
export const RESET_LOAD_OPTIMIZATION_STATE = 'RESET_LOAD_OPTIMIZATION_STATE';
