name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run Integration Tests
      run: |
        cd frontend
        npm run test:integration
        
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourStrong!Passw0rd
        ports:
          - 1433:1433
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: |
        cd backend
        npm install
        
    - name: Setup Database
      run: |
        cd backend
        node src/scripts/setupTestDatabase.js
        
    - name: Run API Tests
      run: |
        cd backend
        npm run test:api
        
    - name: Run Performance Tests
      run: |
        cd backend
        npm run test:performance

  deploy-test:
    needs: [frontend-tests, backend-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Test Environment
      run: |
        echo "Deploying to test environment..."
        # 여기에 테스트 환경 배포 스크립트 추가
        # 예: npm run deploy:test
